//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.11 at 05:20:16 μμ EEST 
//


package org.openiot.commons.osdspec.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}applicationDescriptiveID"/>
 *         &lt;element ref="{}OSMO" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="oamoID" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicationDescriptiveID",
    "osmo"
})
@XmlRootElement(name = "OAMO")
public class OAMO {

    @XmlElement(required = true)
    protected ApplicationDescriptiveID applicationDescriptiveID;
    @XmlElement(name = "OSMO", required = true)
    protected List<OSMO> osmo;
    @XmlAttribute(name = "oamoID")
    @XmlSchemaType(name = "anyURI")
    protected String oamoID;

    /**
     * Gets the value of the applicationDescriptiveID property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationDescriptiveID }
     *     
     */
    public ApplicationDescriptiveID getApplicationDescriptiveID() {
        return applicationDescriptiveID;
    }

    /**
     * Sets the value of the applicationDescriptiveID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationDescriptiveID }
     *     
     */
    public void setApplicationDescriptiveID(ApplicationDescriptiveID value) {
        this.applicationDescriptiveID = value;
    }

    /**
     * Gets the value of the osmo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the osmo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOSMO().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OSMO }
     * 
     * 
     */
    public List<OSMO> getOSMO() {
        if (osmo == null) {
            osmo = new ArrayList<OSMO>();
        }
        return this.osmo;
    }

    /**
     * Gets the value of the oamoID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOamoID() {
        return oamoID;
    }

    /**
     * Sets the value of the oamoID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOamoID(String value) {
        this.oamoID = value;
    }

}
