package org.openiot.ld4s.vocabulary;

/* CVS $Id: $ */
 
import com.hp.hpl.jena.ontology.ObjectProperty;
import com.hp.hpl.jena.ontology.OntModel;
import com.hp.hpl.jena.ontology.OntModelSpec;
import com.hp.hpl.jena.rdf.model.ModelFactory;
import com.hp.hpl.jena.rdf.model.Resource;
 
/**
 * Vocabulary definitions from geonames.rdf 
 * @author Auto-generated by schemagen on 22 Sep 2012 13:20 
 */
public class GeoVocab {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel(OntModelSpec.OWL_MEM, null);
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.geonames.org/ontology#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    
    public static final ObjectProperty PARENT_COUNTRY = m_model
    .createObjectProperty(NS+"parentCountry");
    public static final ObjectProperty PARENT_ADM1 = m_model
    .createObjectProperty(NS+"parentADM1");
    public static final ObjectProperty PARENT_ADM2 = m_model
    .createObjectProperty(NS+"parentADM2");
    public static final ObjectProperty PARENT_ADM3 = m_model
    .createObjectProperty(NS+"parentADM3");
    public static final ObjectProperty POPULATION= m_model
    .createObjectProperty(NS+"population");
    public static final ObjectProperty NEARBY_FEATURES= m_model
    .createObjectProperty(NS+"nearbyFeatures");
    
    
    /** <p>A class of features.</p> */
    public static final Resource Class = m_model.createResource( "http://www.geonames.org/ontology#Class" );
    
    /** <p>A feature code.</p> */
    public static final Resource Code = m_model.createResource( "http://www.geonames.org/ontology#Code" );
    
    /** <p>A geographical object uniquely defined by its geonames id.</p> */
    public static final Resource Feature = m_model.createResource( "http://www.geonames.org/ontology#Feature" );
    
    /** <p>A Web page displaying a map</p> */
    public static final Resource Map = m_model.createResource( "http://www.geonames.org/ontology#Map" );
    
    /** <p>A Document containing RDF description of one or several features.</p> */
    public static final Resource RDFData = m_model.createResource( "http://www.geonames.org/ontology#RDFData" );
    
    /** <p>A Wikipedia article</p> */
    public static final Resource WikipediaArticle = m_model.createResource( "http://www.geonames.org/ontology#WikipediaArticle" );
    
    /** <p>country, state, region ...</p> */
    public static final Resource A = m_model.createResource( "http://www.geonames.org/ontology#A" );
    
    public static final Resource A_ADM1 = m_model.createResource( "http://www.geonames.org/ontology#A.ADM1" );
    
    public static final Resource A_ADM2 = m_model.createResource( "http://www.geonames.org/ontology#A.ADM2" );
    
    public static final Resource A_ADM3 = m_model.createResource( "http://www.geonames.org/ontology#A.ADM3" );
    
    public static final Resource A_ADM4 = m_model.createResource( "http://www.geonames.org/ontology#A.ADM4" );
    
    public static final Resource A_ADM5 = m_model.createResource( "http://www.geonames.org/ontology#A.ADM5" );
    
    public static final Resource A_ADMD = m_model.createResource( "http://www.geonames.org/ontology#A.ADMD" );
    
    public static final Resource A_LTER = m_model.createResource( "http://www.geonames.org/ontology#A.LTER" );
    
    public static final Resource A_PCL = m_model.createResource( "http://www.geonames.org/ontology#A.PCL" );
    
    public static final Resource A_PCLD = m_model.createResource( "http://www.geonames.org/ontology#A.PCLD" );
    
    public static final Resource A_PCLF = m_model.createResource( "http://www.geonames.org/ontology#A.PCLF" );
    
    public static final Resource A_PCLI = m_model.createResource( "http://www.geonames.org/ontology#A.PCLI" );
    
    public static final Resource A_PCLIX = m_model.createResource( "http://www.geonames.org/ontology#A.PCLIX" );
    
    public static final Resource A_PCLS = m_model.createResource( "http://www.geonames.org/ontology#A.PCLS" );
    
    public static final Resource A_PRSH = m_model.createResource( "http://www.geonames.org/ontology#A.PRSH" );
    
    public static final Resource A_TERR = m_model.createResource( "http://www.geonames.org/ontology#A.TERR" );
    
    public static final Resource A_ZN = m_model.createResource( "http://www.geonames.org/ontology#A.ZN" );
    
    public static final Resource A_ZNB = m_model.createResource( "http://www.geonames.org/ontology#A.ZNB" );
    
    /** <p>stream, lake, ...</p> */
    public static final Resource H = m_model.createResource( "http://www.geonames.org/ontology#H" );
    
    public static final Resource H_AIRS = m_model.createResource( "http://www.geonames.org/ontology#H.AIRS" );
    
    public static final Resource H_ANCH = m_model.createResource( "http://www.geonames.org/ontology#H.ANCH" );
    
    public static final Resource H_BAY = m_model.createResource( "http://www.geonames.org/ontology#H.BAY" );
    
    public static final Resource H_BAYS = m_model.createResource( "http://www.geonames.org/ontology#H.BAYS" );
    
    public static final Resource H_BGHT = m_model.createResource( "http://www.geonames.org/ontology#H.BGHT" );
    
    public static final Resource H_BNK = m_model.createResource( "http://www.geonames.org/ontology#H.BNK" );
    
    public static final Resource H_BNKR = m_model.createResource( "http://www.geonames.org/ontology#H.BNKR" );
    
    public static final Resource H_BNKX = m_model.createResource( "http://www.geonames.org/ontology#H.BNKX" );
    
    public static final Resource H_BOG = m_model.createResource( "http://www.geonames.org/ontology#H.BOG" );
    
    public static final Resource H_CAPG = m_model.createResource( "http://www.geonames.org/ontology#H.CAPG" );
    
    public static final Resource H_CHN = m_model.createResource( "http://www.geonames.org/ontology#H.CHN" );
    
    public static final Resource H_CHNL = m_model.createResource( "http://www.geonames.org/ontology#H.CHNL" );
    
    public static final Resource H_CHNM = m_model.createResource( "http://www.geonames.org/ontology#H.CHNM" );
    
    public static final Resource H_CHNN = m_model.createResource( "http://www.geonames.org/ontology#H.CHNN" );
    
    public static final Resource H_CNFL = m_model.createResource( "http://www.geonames.org/ontology#H.CNFL" );
    
    public static final Resource H_CNL = m_model.createResource( "http://www.geonames.org/ontology#H.CNL" );
    
    public static final Resource H_CNLA = m_model.createResource( "http://www.geonames.org/ontology#H.CNLA" );
    
    public static final Resource H_CNLB = m_model.createResource( "http://www.geonames.org/ontology#H.CNLB" );
    
    public static final Resource H_CNLD = m_model.createResource( "http://www.geonames.org/ontology#H.CNLD" );
    
    public static final Resource H_CNLI = m_model.createResource( "http://www.geonames.org/ontology#H.CNLI" );
    
    public static final Resource H_CNLN = m_model.createResource( "http://www.geonames.org/ontology#H.CNLN" );
    
    public static final Resource H_CNLQ = m_model.createResource( "http://www.geonames.org/ontology#H.CNLQ" );
    
    public static final Resource H_CNLSB = m_model.createResource( "http://www.geonames.org/ontology#H.CNLSB" );
    
    public static final Resource H_CNLX = m_model.createResource( "http://www.geonames.org/ontology#H.CNLX" );
    
    public static final Resource H_COVE = m_model.createResource( "http://www.geonames.org/ontology#H.COVE" );
    
    public static final Resource H_CRKT = m_model.createResource( "http://www.geonames.org/ontology#H.CRKT" );
    
    public static final Resource H_CRNT = m_model.createResource( "http://www.geonames.org/ontology#H.CRNT" );
    
    public static final Resource H_CUTF = m_model.createResource( "http://www.geonames.org/ontology#H.CUTF" );
    
    public static final Resource H_DCK = m_model.createResource( "http://www.geonames.org/ontology#H.DCK" );
    
    public static final Resource H_DCKB = m_model.createResource( "http://www.geonames.org/ontology#H.DCKB" );
    
    public static final Resource H_DOMG = m_model.createResource( "http://www.geonames.org/ontology#H.DOMG" );
    
    public static final Resource H_DPRG = m_model.createResource( "http://www.geonames.org/ontology#H.DPRG" );
    
    public static final Resource H_DTCH = m_model.createResource( "http://www.geonames.org/ontology#H.DTCH" );
    
    public static final Resource H_DTCHD = m_model.createResource( "http://www.geonames.org/ontology#H.DTCHD" );
    
    public static final Resource H_DTCHI = m_model.createResource( "http://www.geonames.org/ontology#H.DTCHI" );
    
    public static final Resource H_DTCHM = m_model.createResource( "http://www.geonames.org/ontology#H.DTCHM" );
    
    public static final Resource H_ESTY = m_model.createResource( "http://www.geonames.org/ontology#H.ESTY" );
    
    public static final Resource H_FISH = m_model.createResource( "http://www.geonames.org/ontology#H.FISH" );
    
    public static final Resource H_FJD = m_model.createResource( "http://www.geonames.org/ontology#H.FJD" );
    
    public static final Resource H_FJDS = m_model.createResource( "http://www.geonames.org/ontology#H.FJDS" );
    
    public static final Resource H_FLLS = m_model.createResource( "http://www.geonames.org/ontology#H.FLLS" );
    
    public static final Resource H_FLLSX = m_model.createResource( "http://www.geonames.org/ontology#H.FLLSX" );
    
    public static final Resource H_FLTM = m_model.createResource( "http://www.geonames.org/ontology#H.FLTM" );
    
    public static final Resource H_FLTT = m_model.createResource( "http://www.geonames.org/ontology#H.FLTT" );
    
    public static final Resource H_GLCR = m_model.createResource( "http://www.geonames.org/ontology#H.GLCR" );
    
    public static final Resource H_GULF = m_model.createResource( "http://www.geonames.org/ontology#H.GULF" );
    
    public static final Resource H_GYSR = m_model.createResource( "http://www.geonames.org/ontology#H.GYSR" );
    
    public static final Resource H_HBR = m_model.createResource( "http://www.geonames.org/ontology#H.HBR" );
    
    public static final Resource H_HBRX = m_model.createResource( "http://www.geonames.org/ontology#H.HBRX" );
    
    public static final Resource H_INLT = m_model.createResource( "http://www.geonames.org/ontology#H.INLT" );
    
    public static final Resource H_INLTQ = m_model.createResource( "http://www.geonames.org/ontology#H.INLTQ" );
    
    public static final Resource H_LBED = m_model.createResource( "http://www.geonames.org/ontology#H.LBED" );
    
    public static final Resource H_LGN = m_model.createResource( "http://www.geonames.org/ontology#H.LGN" );
    
    public static final Resource H_LGNS = m_model.createResource( "http://www.geonames.org/ontology#H.LGNS" );
    
    public static final Resource H_LGNX = m_model.createResource( "http://www.geonames.org/ontology#H.LGNX" );
    
    public static final Resource H_LK = m_model.createResource( "http://www.geonames.org/ontology#H.LK" );
    
    public static final Resource H_LKC = m_model.createResource( "http://www.geonames.org/ontology#H.LKC" );
    
    public static final Resource H_LKI = m_model.createResource( "http://www.geonames.org/ontology#H.LKI" );
    
    public static final Resource H_LKN = m_model.createResource( "http://www.geonames.org/ontology#H.LKN" );
    
    public static final Resource H_LKNI = m_model.createResource( "http://www.geonames.org/ontology#H.LKNI" );
    
    public static final Resource H_LKO = m_model.createResource( "http://www.geonames.org/ontology#H.LKO" );
    
    public static final Resource H_LKOI = m_model.createResource( "http://www.geonames.org/ontology#H.LKOI" );
    
    public static final Resource H_LKS = m_model.createResource( "http://www.geonames.org/ontology#H.LKS" );
    
    public static final Resource H_LKSB = m_model.createResource( "http://www.geonames.org/ontology#H.LKSB" );
    
    public static final Resource H_LKSC = m_model.createResource( "http://www.geonames.org/ontology#H.LKSC" );
    
    public static final Resource H_LKSI = m_model.createResource( "http://www.geonames.org/ontology#H.LKSI" );
    
    public static final Resource H_LKSN = m_model.createResource( "http://www.geonames.org/ontology#H.LKSN" );
    
    public static final Resource H_LKSNI = m_model.createResource( "http://www.geonames.org/ontology#H.LKSNI" );
    
    public static final Resource H_LKX = m_model.createResource( "http://www.geonames.org/ontology#H.LKX" );
    
    public static final Resource H_MFGN = m_model.createResource( "http://www.geonames.org/ontology#H.MFGN" );
    
    public static final Resource H_MGV = m_model.createResource( "http://www.geonames.org/ontology#H.MGV" );
    
    public static final Resource H_MOOR = m_model.createResource( "http://www.geonames.org/ontology#H.MOOR" );
    
    public static final Resource H_MRSH = m_model.createResource( "http://www.geonames.org/ontology#H.MRSH" );
    
    public static final Resource H_MRSHN = m_model.createResource( "http://www.geonames.org/ontology#H.MRSHN" );
    
    public static final Resource H_NRWS = m_model.createResource( "http://www.geonames.org/ontology#H.NRWS" );
    
    public static final Resource H_OCN = m_model.createResource( "http://www.geonames.org/ontology#H.OCN" );
    
    public static final Resource H_OVF = m_model.createResource( "http://www.geonames.org/ontology#H.OVF" );
    
    public static final Resource H_PND = m_model.createResource( "http://www.geonames.org/ontology#H.PND" );
    
    public static final Resource H_PNDI = m_model.createResource( "http://www.geonames.org/ontology#H.PNDI" );
    
    public static final Resource H_PNDN = m_model.createResource( "http://www.geonames.org/ontology#H.PNDN" );
    
    public static final Resource H_PNDNI = m_model.createResource( "http://www.geonames.org/ontology#H.PNDNI" );
    
    public static final Resource H_PNDS = m_model.createResource( "http://www.geonames.org/ontology#H.PNDS" );
    
    public static final Resource H_PNDSF = m_model.createResource( "http://www.geonames.org/ontology#H.PNDSF" );
    
    public static final Resource H_PNDSI = m_model.createResource( "http://www.geonames.org/ontology#H.PNDSI" );
    
    public static final Resource H_PNDSN = m_model.createResource( "http://www.geonames.org/ontology#H.PNDSN" );
    
    public static final Resource H_POOL = m_model.createResource( "http://www.geonames.org/ontology#H.POOL" );
    
    public static final Resource H_POOLI = m_model.createResource( "http://www.geonames.org/ontology#H.POOLI" );
    
    public static final Resource H_RCH = m_model.createResource( "http://www.geonames.org/ontology#H.RCH" );
    
    public static final Resource H_RDGG = m_model.createResource( "http://www.geonames.org/ontology#H.RDGG" );
    
    public static final Resource H_RDST = m_model.createResource( "http://www.geonames.org/ontology#H.RDST" );
    
    public static final Resource H_RF = m_model.createResource( "http://www.geonames.org/ontology#H.RF" );
    
    public static final Resource H_RFC = m_model.createResource( "http://www.geonames.org/ontology#H.RFC" );
    
    public static final Resource H_RFX = m_model.createResource( "http://www.geonames.org/ontology#H.RFX" );
    
    public static final Resource H_RPDS = m_model.createResource( "http://www.geonames.org/ontology#H.RPDS" );
    
    public static final Resource H_RSV = m_model.createResource( "http://www.geonames.org/ontology#H.RSV" );
    
    public static final Resource H_RSVI = m_model.createResource( "http://www.geonames.org/ontology#H.RSVI" );
    
    public static final Resource H_RSVT = m_model.createResource( "http://www.geonames.org/ontology#H.RSVT" );
    
    public static final Resource H_RVN = m_model.createResource( "http://www.geonames.org/ontology#H.RVN" );
    
    public static final Resource H_SBKH = m_model.createResource( "http://www.geonames.org/ontology#H.SBKH" );
    
    public static final Resource H_SD = m_model.createResource( "http://www.geonames.org/ontology#H.SD" );
    
    public static final Resource H_SEA = m_model.createResource( "http://www.geonames.org/ontology#H.SEA" );
    
    public static final Resource H_SHOL = m_model.createResource( "http://www.geonames.org/ontology#H.SHOL" );
    
    public static final Resource H_SILL = m_model.createResource( "http://www.geonames.org/ontology#H.SILL" );
    
    public static final Resource H_SPNG = m_model.createResource( "http://www.geonames.org/ontology#H.SPNG" );
    
    public static final Resource H_SPNS = m_model.createResource( "http://www.geonames.org/ontology#H.SPNS" );
    
    public static final Resource H_SPNT = m_model.createResource( "http://www.geonames.org/ontology#H.SPNT" );
    
    public static final Resource H_STM = m_model.createResource( "http://www.geonames.org/ontology#H.STM" );
    
    public static final Resource H_STMA = m_model.createResource( "http://www.geonames.org/ontology#H.STMA" );
    
    public static final Resource H_STMB = m_model.createResource( "http://www.geonames.org/ontology#H.STMB" );
    
    public static final Resource H_STMC = m_model.createResource( "http://www.geonames.org/ontology#H.STMC" );
    
    public static final Resource H_STMD = m_model.createResource( "http://www.geonames.org/ontology#H.STMD" );
    
    public static final Resource H_STMH = m_model.createResource( "http://www.geonames.org/ontology#H.STMH" );
    
    public static final Resource H_STMI = m_model.createResource( "http://www.geonames.org/ontology#H.STMI" );
    
    public static final Resource H_STMIX = m_model.createResource( "http://www.geonames.org/ontology#H.STMIX" );
    
    public static final Resource H_STMM = m_model.createResource( "http://www.geonames.org/ontology#H.STMM" );
    
    public static final Resource H_STMQ = m_model.createResource( "http://www.geonames.org/ontology#H.STMQ" );
    
    public static final Resource H_STMS = m_model.createResource( "http://www.geonames.org/ontology#H.STMS" );
    
    public static final Resource H_STMSB = m_model.createResource( "http://www.geonames.org/ontology#H.STMSB" );
    
    public static final Resource H_STMX = m_model.createResource( "http://www.geonames.org/ontology#H.STMX" );
    
    public static final Resource H_STRT = m_model.createResource( "http://www.geonames.org/ontology#H.STRT" );
    
    public static final Resource H_SWMP = m_model.createResource( "http://www.geonames.org/ontology#H.SWMP" );
    
    public static final Resource H_SYSI = m_model.createResource( "http://www.geonames.org/ontology#H.SYSI" );
    
    public static final Resource H_TNLC = m_model.createResource( "http://www.geonames.org/ontology#H.TNLC" );
    
    public static final Resource H_WAD = m_model.createResource( "http://www.geonames.org/ontology#H.WAD" );
    
    public static final Resource H_WADB = m_model.createResource( "http://www.geonames.org/ontology#H.WADB" );
    
    public static final Resource H_WADJ = m_model.createResource( "http://www.geonames.org/ontology#H.WADJ" );
    
    public static final Resource H_WADM = m_model.createResource( "http://www.geonames.org/ontology#H.WADM" );
    
    public static final Resource H_WADS = m_model.createResource( "http://www.geonames.org/ontology#H.WADS" );
    
    public static final Resource H_WADX = m_model.createResource( "http://www.geonames.org/ontology#H.WADX" );
    
    public static final Resource H_WHRL = m_model.createResource( "http://www.geonames.org/ontology#H.WHRL" );
    
    public static final Resource H_WLL = m_model.createResource( "http://www.geonames.org/ontology#H.WLL" );
    
    public static final Resource H_WLLQ = m_model.createResource( "http://www.geonames.org/ontology#H.WLLQ" );
    
    public static final Resource H_WLLS = m_model.createResource( "http://www.geonames.org/ontology#H.WLLS" );
    
    public static final Resource H_WTLD = m_model.createResource( "http://www.geonames.org/ontology#H.WTLD" );
    
    public static final Resource H_WTLDI = m_model.createResource( "http://www.geonames.org/ontology#H.WTLDI" );
    
    public static final Resource H_WTRC = m_model.createResource( "http://www.geonames.org/ontology#H.WTRC" );
    
    public static final Resource H_WTRH = m_model.createResource( "http://www.geonames.org/ontology#H.WTRH" );
    
    /** <p>parks,area, ...</p> */
    public static final Resource L = m_model.createResource( "http://www.geonames.org/ontology#L" );
    
    public static final Resource L_AGRC = m_model.createResource( "http://www.geonames.org/ontology#L.AGRC" );
    
    public static final Resource L_AMUS = m_model.createResource( "http://www.geonames.org/ontology#L.AMUS" );
    
    public static final Resource L_AREA = m_model.createResource( "http://www.geonames.org/ontology#L.AREA" );
    
    public static final Resource L_BSND = m_model.createResource( "http://www.geonames.org/ontology#L.BSND" );
    
    public static final Resource L_BSNP = m_model.createResource( "http://www.geonames.org/ontology#L.BSNP" );
    
    public static final Resource L_BTL = m_model.createResource( "http://www.geonames.org/ontology#L.BTL" );
    
    public static final Resource L_CLG = m_model.createResource( "http://www.geonames.org/ontology#L.CLG" );
    
    public static final Resource L_CMN = m_model.createResource( "http://www.geonames.org/ontology#L.CMN" );
    
    public static final Resource L_CNS = m_model.createResource( "http://www.geonames.org/ontology#L.CNS" );
    
    public static final Resource L_COLF = m_model.createResource( "http://www.geonames.org/ontology#L.COLF" );
    
    public static final Resource L_CONT = m_model.createResource( "http://www.geonames.org/ontology#L.CONT" );
    
    public static final Resource L_CST = m_model.createResource( "http://www.geonames.org/ontology#L.CST" );
    
    public static final Resource L_CTRB = m_model.createResource( "http://www.geonames.org/ontology#L.CTRB" );
    
    public static final Resource L_DEVH = m_model.createResource( "http://www.geonames.org/ontology#L.DEVH" );
    
    public static final Resource L_FLD = m_model.createResource( "http://www.geonames.org/ontology#L.FLD" );
    
    public static final Resource L_FLDI = m_model.createResource( "http://www.geonames.org/ontology#L.FLDI" );
    
    public static final Resource L_GASF = m_model.createResource( "http://www.geonames.org/ontology#L.GASF" );
    
    public static final Resource L_GRAZ = m_model.createResource( "http://www.geonames.org/ontology#L.GRAZ" );
    
    public static final Resource L_GVL = m_model.createResource( "http://www.geonames.org/ontology#L.GVL" );
    
    public static final Resource L_INDS = m_model.createResource( "http://www.geonames.org/ontology#L.INDS" );
    
    public static final Resource L_LAND = m_model.createResource( "http://www.geonames.org/ontology#L.LAND" );
    
    public static final Resource L_LCTY = m_model.createResource( "http://www.geonames.org/ontology#L.LCTY" );
    
    public static final Resource L_MILB = m_model.createResource( "http://www.geonames.org/ontology#L.MILB" );
    
    public static final Resource L_MNA = m_model.createResource( "http://www.geonames.org/ontology#L.MNA" );
    
    public static final Resource L_MVA = m_model.createResource( "http://www.geonames.org/ontology#L.MVA" );
    
    public static final Resource L_NVB = m_model.createResource( "http://www.geonames.org/ontology#L.NVB" );
    
    public static final Resource L_OAS = m_model.createResource( "http://www.geonames.org/ontology#L.OAS" );
    
    public static final Resource L_OILF = m_model.createResource( "http://www.geonames.org/ontology#L.OILF" );
    
    public static final Resource L_PEAT = m_model.createResource( "http://www.geonames.org/ontology#L.PEAT" );
    
    public static final Resource L_PRK = m_model.createResource( "http://www.geonames.org/ontology#L.PRK" );
    
    public static final Resource L_PRT = m_model.createResource( "http://www.geonames.org/ontology#L.PRT" );
    
    public static final Resource L_QCKS = m_model.createResource( "http://www.geonames.org/ontology#L.QCKS" );
    
    public static final Resource L_REP = m_model.createResource( "http://www.geonames.org/ontology#L.REP" );
    
    public static final Resource L_RES = m_model.createResource( "http://www.geonames.org/ontology#L.RES" );
    
    public static final Resource L_RESA = m_model.createResource( "http://www.geonames.org/ontology#L.RESA" );
    
    public static final Resource L_RESF = m_model.createResource( "http://www.geonames.org/ontology#L.RESF" );
    
    public static final Resource L_RESH = m_model.createResource( "http://www.geonames.org/ontology#L.RESH" );
    
    public static final Resource L_RESN = m_model.createResource( "http://www.geonames.org/ontology#L.RESN" );
    
    public static final Resource L_RESP = m_model.createResource( "http://www.geonames.org/ontology#L.RESP" );
    
    public static final Resource L_RESV = m_model.createResource( "http://www.geonames.org/ontology#L.RESV" );
    
    public static final Resource L_RESW = m_model.createResource( "http://www.geonames.org/ontology#L.RESW" );
    
    public static final Resource L_RGN = m_model.createResource( "http://www.geonames.org/ontology#L.RGN" );
    
    public static final Resource L_RGNE = m_model.createResource( "http://www.geonames.org/ontology#L.RGNE" );
    
    public static final Resource L_RGNL = m_model.createResource( "http://www.geonames.org/ontology#L.RGNL" );
    
    public static final Resource L_RNGA = m_model.createResource( "http://www.geonames.org/ontology#L.RNGA" );
    
    public static final Resource L_SALT = m_model.createResource( "http://www.geonames.org/ontology#L.SALT" );
    
    public static final Resource L_SNOW = m_model.createResource( "http://www.geonames.org/ontology#L.SNOW" );
    
    public static final Resource L_TRB = m_model.createResource( "http://www.geonames.org/ontology#L.TRB" );
    
    public static final Resource L_ZZZZZ = m_model.createResource( "http://www.geonames.org/ontology#L.ZZZZZ" );
    
    /** <p>city, village,...</p> */
    public static final Resource P = m_model.createResource( "http://www.geonames.org/ontology#P" );
    
    public static final Resource P_PPL = m_model.createResource( "http://www.geonames.org/ontology#P.PPL" );
    
    public static final Resource P_PPLA = m_model.createResource( "http://www.geonames.org/ontology#P.PPLA" );
    
    public static final Resource P_PPLA2 = m_model.createResource( "http://www.geonames.org/ontology#P.PPLA2" );
    
    public static final Resource P_PPLA3 = m_model.createResource( "http://www.geonames.org/ontology#P.PPLA3" );
    
    public static final Resource P_PPLA4 = m_model.createResource( "http://www.geonames.org/ontology#P.PPLA4" );
    
    public static final Resource P_PPLC = m_model.createResource( "http://www.geonames.org/ontology#P.PPLC" );
    
    public static final Resource P_PPLF = m_model.createResource( "http://www.geonames.org/ontology#P.PPLF" );
    
    public static final Resource P_PPLG = m_model.createResource( "http://www.geonames.org/ontology#P.PPLG" );
    
    public static final Resource P_PPLL = m_model.createResource( "http://www.geonames.org/ontology#P.PPLL" );
    
    public static final Resource P_PPLQ = m_model.createResource( "http://www.geonames.org/ontology#P.PPLQ" );
    
    public static final Resource P_PPLR = m_model.createResource( "http://www.geonames.org/ontology#P.PPLR" );
    
    public static final Resource P_PPLS = m_model.createResource( "http://www.geonames.org/ontology#P.PPLS" );
    
    public static final Resource P_PPLW = m_model.createResource( "http://www.geonames.org/ontology#P.PPLW" );
    
    public static final Resource P_PPLX = m_model.createResource( "http://www.geonames.org/ontology#P.PPLX" );
    
    public static final Resource P_STLMT = m_model.createResource( "http://www.geonames.org/ontology#P.STLMT" );
    
    /** <p>road, railroad, ...</p> */
    public static final Resource R = m_model.createResource( "http://www.geonames.org/ontology#R" );
    
    public static final Resource R_CSWY = m_model.createResource( "http://www.geonames.org/ontology#R.CSWY" );
    
    public static final Resource R_CSWYQ = m_model.createResource( "http://www.geonames.org/ontology#R.CSWYQ" );
    
    public static final Resource R_OILP = m_model.createResource( "http://www.geonames.org/ontology#R.OILP" );
    
    public static final Resource R_PRMN = m_model.createResource( "http://www.geonames.org/ontology#R.PRMN" );
    
    public static final Resource R_PTGE = m_model.createResource( "http://www.geonames.org/ontology#R.PTGE" );
    
    public static final Resource R_RD = m_model.createResource( "http://www.geonames.org/ontology#R.RD" );
    
    public static final Resource R_RDA = m_model.createResource( "http://www.geonames.org/ontology#R.RDA" );
    
    public static final Resource R_RDB = m_model.createResource( "http://www.geonames.org/ontology#R.RDB" );
    
    public static final Resource R_RDCUT = m_model.createResource( "http://www.geonames.org/ontology#R.RDCUT" );
    
    public static final Resource R_RDJCT = m_model.createResource( "http://www.geonames.org/ontology#R.RDJCT" );
    
    public static final Resource R_RJCT = m_model.createResource( "http://www.geonames.org/ontology#R.RJCT" );
    
    public static final Resource R_RR = m_model.createResource( "http://www.geonames.org/ontology#R.RR" );
    
    public static final Resource R_RRQ = m_model.createResource( "http://www.geonames.org/ontology#R.RRQ" );
    
    public static final Resource R_RTE = m_model.createResource( "http://www.geonames.org/ontology#R.RTE" );
    
    public static final Resource R_RYD = m_model.createResource( "http://www.geonames.org/ontology#R.RYD" );
    
    public static final Resource R_ST = m_model.createResource( "http://www.geonames.org/ontology#R.ST" );
    
    public static final Resource R_STKR = m_model.createResource( "http://www.geonames.org/ontology#R.STKR" );
    
    public static final Resource R_TNL = m_model.createResource( "http://www.geonames.org/ontology#R.TNL" );
    
    public static final Resource R_TNLN = m_model.createResource( "http://www.geonames.org/ontology#R.TNLN" );
    
    public static final Resource R_TNLRD = m_model.createResource( "http://www.geonames.org/ontology#R.TNLRD" );
    
    public static final Resource R_TNLRR = m_model.createResource( "http://www.geonames.org/ontology#R.TNLRR" );
    
    public static final Resource R_TNLS = m_model.createResource( "http://www.geonames.org/ontology#R.TNLS" );
    
    public static final Resource R_TRL = m_model.createResource( "http://www.geonames.org/ontology#R.TRL" );
    
    /** <p>spot, building, farm, ...</p> */
    public static final Resource S = m_model.createResource( "http://www.geonames.org/ontology#S" );
    
    public static final Resource S_ADMF = m_model.createResource( "http://www.geonames.org/ontology#S.ADMF" );
    
    public static final Resource S_AGRF = m_model.createResource( "http://www.geonames.org/ontology#S.AGRF" );
    
    public static final Resource S_AIRB = m_model.createResource( "http://www.geonames.org/ontology#S.AIRB" );
    
    public static final Resource S_AIRF = m_model.createResource( "http://www.geonames.org/ontology#S.AIRF" );
    
    public static final Resource S_AIRH = m_model.createResource( "http://www.geonames.org/ontology#S.AIRH" );
    
    public static final Resource S_AIRP = m_model.createResource( "http://www.geonames.org/ontology#S.AIRP" );
    
    public static final Resource S_AIRQ = m_model.createResource( "http://www.geonames.org/ontology#S.AIRQ" );
    
    public static final Resource S_AMTH = m_model.createResource( "http://www.geonames.org/ontology#S.AMTH" );
    
    public static final Resource S_ANS = m_model.createResource( "http://www.geonames.org/ontology#S.ANS" );
    
    public static final Resource S_AQC = m_model.createResource( "http://www.geonames.org/ontology#S.AQC" );
    
    public static final Resource S_ARCH = m_model.createResource( "http://www.geonames.org/ontology#S.ARCH" );
    
    public static final Resource S_ASTR = m_model.createResource( "http://www.geonames.org/ontology#S.ASTR" );
    
    public static final Resource S_ASYL = m_model.createResource( "http://www.geonames.org/ontology#S.ASYL" );
    
    public static final Resource S_ATHF = m_model.createResource( "http://www.geonames.org/ontology#S.ATHF" );
    
    public static final Resource S_ATM = m_model.createResource( "http://www.geonames.org/ontology#S.ATM" );
    
    public static final Resource S_BANK = m_model.createResource( "http://www.geonames.org/ontology#S.BANK" );
    
    public static final Resource S_BCN = m_model.createResource( "http://www.geonames.org/ontology#S.BCN" );
    
    public static final Resource S_BDG = m_model.createResource( "http://www.geonames.org/ontology#S.BDG" );
    
    public static final Resource S_BDGQ = m_model.createResource( "http://www.geonames.org/ontology#S.BDGQ" );
    
    public static final Resource S_BLDG = m_model.createResource( "http://www.geonames.org/ontology#S.BLDG" );
    
    public static final Resource S_BLDO = m_model.createResource( "http://www.geonames.org/ontology#S.BLDO" );
    
    public static final Resource S_BP = m_model.createResource( "http://www.geonames.org/ontology#S.BP" );
    
    public static final Resource S_BRKS = m_model.createResource( "http://www.geonames.org/ontology#S.BRKS" );
    
    public static final Resource S_BRKW = m_model.createResource( "http://www.geonames.org/ontology#S.BRKW" );
    
    public static final Resource S_BSTN = m_model.createResource( "http://www.geonames.org/ontology#S.BSTN" );
    
    public static final Resource S_BTYD = m_model.createResource( "http://www.geonames.org/ontology#S.BTYD" );
    
    public static final Resource S_BUR = m_model.createResource( "http://www.geonames.org/ontology#S.BUR" );
    
    public static final Resource S_BUSTN = m_model.createResource( "http://www.geonames.org/ontology#S.BUSTN" );
    
    public static final Resource S_BUSTP = m_model.createResource( "http://www.geonames.org/ontology#S.BUSTP" );
    
    public static final Resource S_CARN = m_model.createResource( "http://www.geonames.org/ontology#S.CARN" );
    
    public static final Resource S_CAVE = m_model.createResource( "http://www.geonames.org/ontology#S.CAVE" );
    
    public static final Resource S_CCL = m_model.createResource( "http://www.geonames.org/ontology#S.CCL" );
    
    public static final Resource S_CH = m_model.createResource( "http://www.geonames.org/ontology#S.CH" );
    
    public static final Resource S_CMP = m_model.createResource( "http://www.geonames.org/ontology#S.CMP" );
    
    public static final Resource S_CMPL = m_model.createResource( "http://www.geonames.org/ontology#S.CMPL" );
    
    public static final Resource S_CMPLA = m_model.createResource( "http://www.geonames.org/ontology#S.CMPLA" );
    
    public static final Resource S_CMPMN = m_model.createResource( "http://www.geonames.org/ontology#S.CMPMN" );
    
    public static final Resource S_CMPO = m_model.createResource( "http://www.geonames.org/ontology#S.CMPO" );
    
    public static final Resource S_CMPQ = m_model.createResource( "http://www.geonames.org/ontology#S.CMPQ" );
    
    public static final Resource S_CMPRF = m_model.createResource( "http://www.geonames.org/ontology#S.CMPRF" );
    
    public static final Resource S_CMTY = m_model.createResource( "http://www.geonames.org/ontology#S.CMTY" );
    
    public static final Resource S_COMC = m_model.createResource( "http://www.geonames.org/ontology#S.COMC" );
    
    public static final Resource S_CRRL = m_model.createResource( "http://www.geonames.org/ontology#S.CRRL" );
    
    public static final Resource S_CSNO = m_model.createResource( "http://www.geonames.org/ontology#S.CSNO" );
    
    public static final Resource S_CSTL = m_model.createResource( "http://www.geonames.org/ontology#S.CSTL" );
    
    public static final Resource S_CSTM = m_model.createResource( "http://www.geonames.org/ontology#S.CSTM" );
    
    public static final Resource S_CTHSE = m_model.createResource( "http://www.geonames.org/ontology#S.CTHSE" );
    
    public static final Resource S_CTRA = m_model.createResource( "http://www.geonames.org/ontology#S.CTRA" );
    
    public static final Resource S_CTRCM = m_model.createResource( "http://www.geonames.org/ontology#S.CTRCM" );
    
    public static final Resource S_CTRF = m_model.createResource( "http://www.geonames.org/ontology#S.CTRF" );
    
    public static final Resource S_CTRM = m_model.createResource( "http://www.geonames.org/ontology#S.CTRM" );
    
    public static final Resource S_CTRR = m_model.createResource( "http://www.geonames.org/ontology#S.CTRR" );
    
    public static final Resource S_CTRS = m_model.createResource( "http://www.geonames.org/ontology#S.CTRS" );
    
    public static final Resource S_CVNT = m_model.createResource( "http://www.geonames.org/ontology#S.CVNT" );
    
    public static final Resource S_DAM = m_model.createResource( "http://www.geonames.org/ontology#S.DAM" );
    
    public static final Resource S_DAMQ = m_model.createResource( "http://www.geonames.org/ontology#S.DAMQ" );
    
    public static final Resource S_DAMSB = m_model.createResource( "http://www.geonames.org/ontology#S.DAMSB" );
    
    public static final Resource S_DARY = m_model.createResource( "http://www.geonames.org/ontology#S.DARY" );
    
    public static final Resource S_DCKD = m_model.createResource( "http://www.geonames.org/ontology#S.DCKD" );
    
    public static final Resource S_DCKY = m_model.createResource( "http://www.geonames.org/ontology#S.DCKY" );
    
    public static final Resource S_DIKE = m_model.createResource( "http://www.geonames.org/ontology#S.DIKE" );
    
    public static final Resource S_DIP = m_model.createResource( "http://www.geonames.org/ontology#S.DIP" );
    
    public static final Resource S_DPOF = m_model.createResource( "http://www.geonames.org/ontology#S.DPOF" );
    
    public static final Resource S_EST = m_model.createResource( "http://www.geonames.org/ontology#S.EST" );
    
    public static final Resource S_ESTB = m_model.createResource( "http://www.geonames.org/ontology#S.ESTB" );
    
    public static final Resource S_ESTC = m_model.createResource( "http://www.geonames.org/ontology#S.ESTC" );
    
    public static final Resource S_ESTO = m_model.createResource( "http://www.geonames.org/ontology#S.ESTO" );
    
    public static final Resource S_ESTR = m_model.createResource( "http://www.geonames.org/ontology#S.ESTR" );
    
    public static final Resource S_ESTSG = m_model.createResource( "http://www.geonames.org/ontology#S.ESTSG" );
    
    public static final Resource S_ESTSL = m_model.createResource( "http://www.geonames.org/ontology#S.ESTSL" );
    
    public static final Resource S_ESTT = m_model.createResource( "http://www.geonames.org/ontology#S.ESTT" );
    
    public static final Resource S_ESTX = m_model.createResource( "http://www.geonames.org/ontology#S.ESTX" );
    
    public static final Resource S_FCL = m_model.createResource( "http://www.geonames.org/ontology#S.FCL" );
    
    public static final Resource S_FNDY = m_model.createResource( "http://www.geonames.org/ontology#S.FNDY" );
    
    public static final Resource S_FRM = m_model.createResource( "http://www.geonames.org/ontology#S.FRM" );
    
    public static final Resource S_FRMQ = m_model.createResource( "http://www.geonames.org/ontology#S.FRMQ" );
    
    public static final Resource S_FRMS = m_model.createResource( "http://www.geonames.org/ontology#S.FRMS" );
    
    public static final Resource S_FRMT = m_model.createResource( "http://www.geonames.org/ontology#S.FRMT" );
    
    public static final Resource S_FT = m_model.createResource( "http://www.geonames.org/ontology#S.FT" );
    
    public static final Resource S_FY = m_model.createResource( "http://www.geonames.org/ontology#S.FY" );
    
    public static final Resource S_GATE = m_model.createResource( "http://www.geonames.org/ontology#S.GATE" );
    
    public static final Resource S_GDN = m_model.createResource( "http://www.geonames.org/ontology#S.GDN" );
    
    public static final Resource S_GHAT = m_model.createResource( "http://www.geonames.org/ontology#S.GHAT" );
    
    public static final Resource S_GHSE = m_model.createResource( "http://www.geonames.org/ontology#S.GHSE" );
    
    public static final Resource S_GOSP = m_model.createResource( "http://www.geonames.org/ontology#S.GOSP" );
    
    public static final Resource S_GOVL = m_model.createResource( "http://www.geonames.org/ontology#S.GOVL" );
    
    public static final Resource S_GRVE = m_model.createResource( "http://www.geonames.org/ontology#S.GRVE" );
    
    public static final Resource S_HERM = m_model.createResource( "http://www.geonames.org/ontology#S.HERM" );
    
    public static final Resource S_HLT = m_model.createResource( "http://www.geonames.org/ontology#S.HLT" );
    
    public static final Resource S_HSE = m_model.createResource( "http://www.geonames.org/ontology#S.HSE" );
    
    public static final Resource S_HSEC = m_model.createResource( "http://www.geonames.org/ontology#S.HSEC" );
    
    public static final Resource S_HSP = m_model.createResource( "http://www.geonames.org/ontology#S.HSP" );
    
    public static final Resource S_HSPC = m_model.createResource( "http://www.geonames.org/ontology#S.HSPC" );
    
    public static final Resource S_HSPD = m_model.createResource( "http://www.geonames.org/ontology#S.HSPD" );
    
    public static final Resource S_HSPL = m_model.createResource( "http://www.geonames.org/ontology#S.HSPL" );
    
    public static final Resource S_HSTS = m_model.createResource( "http://www.geonames.org/ontology#S.HSTS" );
    
    public static final Resource S_HTL = m_model.createResource( "http://www.geonames.org/ontology#S.HTL" );
    
    public static final Resource S_HUT = m_model.createResource( "http://www.geonames.org/ontology#S.HUT" );
    
    public static final Resource S_HUTS = m_model.createResource( "http://www.geonames.org/ontology#S.HUTS" );
    
    public static final Resource S_INSM = m_model.createResource( "http://www.geonames.org/ontology#S.INSM" );
    
    public static final Resource S_ITTR = m_model.createResource( "http://www.geonames.org/ontology#S.ITTR" );
    
    public static final Resource S_JTY = m_model.createResource( "http://www.geonames.org/ontology#S.JTY" );
    
    public static final Resource S_LDNG = m_model.createResource( "http://www.geonames.org/ontology#S.LDNG" );
    
    public static final Resource S_LEPC = m_model.createResource( "http://www.geonames.org/ontology#S.LEPC" );
    
    public static final Resource S_LIBR = m_model.createResource( "http://www.geonames.org/ontology#S.LIBR" );
    
    public static final Resource S_LNDF = m_model.createResource( "http://www.geonames.org/ontology#S.LNDF" );
    
    public static final Resource S_LOCK = m_model.createResource( "http://www.geonames.org/ontology#S.LOCK" );
    
    public static final Resource S_LTHSE = m_model.createResource( "http://www.geonames.org/ontology#S.LTHSE" );
    
    public static final Resource S_MALL = m_model.createResource( "http://www.geonames.org/ontology#S.MALL" );
    
    public static final Resource S_MAR = m_model.createResource( "http://www.geonames.org/ontology#S.MAR" );
    
    public static final Resource S_MFG = m_model.createResource( "http://www.geonames.org/ontology#S.MFG" );
    
    public static final Resource S_MFGB = m_model.createResource( "http://www.geonames.org/ontology#S.MFGB" );
    
    public static final Resource S_MFGC = m_model.createResource( "http://www.geonames.org/ontology#S.MFGC" );
    
    public static final Resource S_MFGCU = m_model.createResource( "http://www.geonames.org/ontology#S.MFGCU" );
    
    public static final Resource S_MFGLM = m_model.createResource( "http://www.geonames.org/ontology#S.MFGLM" );
    
    public static final Resource S_MFGM = m_model.createResource( "http://www.geonames.org/ontology#S.MFGM" );
    
    public static final Resource S_MFGPH = m_model.createResource( "http://www.geonames.org/ontology#S.MFGPH" );
    
    public static final Resource S_MFGQ = m_model.createResource( "http://www.geonames.org/ontology#S.MFGQ" );
    
    public static final Resource S_MFGSG = m_model.createResource( "http://www.geonames.org/ontology#S.MFGSG" );
    
    public static final Resource S_MKT = m_model.createResource( "http://www.geonames.org/ontology#S.MKT" );
    
    public static final Resource S_ML = m_model.createResource( "http://www.geonames.org/ontology#S.ML" );
    
    public static final Resource S_MLM = m_model.createResource( "http://www.geonames.org/ontology#S.MLM" );
    
    public static final Resource S_MLO = m_model.createResource( "http://www.geonames.org/ontology#S.MLO" );
    
    public static final Resource S_MLSG = m_model.createResource( "http://www.geonames.org/ontology#S.MLSG" );
    
    public static final Resource S_MLSGQ = m_model.createResource( "http://www.geonames.org/ontology#S.MLSGQ" );
    
    public static final Resource S_MLSW = m_model.createResource( "http://www.geonames.org/ontology#S.MLSW" );
    
    public static final Resource S_MLWND = m_model.createResource( "http://www.geonames.org/ontology#S.MLWND" );
    
    public static final Resource S_MLWTR = m_model.createResource( "http://www.geonames.org/ontology#S.MLWTR" );
    
    public static final Resource S_MN = m_model.createResource( "http://www.geonames.org/ontology#S.MN" );
    
    public static final Resource S_MNAU = m_model.createResource( "http://www.geonames.org/ontology#S.MNAU" );
    
    public static final Resource S_MNC = m_model.createResource( "http://www.geonames.org/ontology#S.MNC" );
    
    public static final Resource S_MNCR = m_model.createResource( "http://www.geonames.org/ontology#S.MNCR" );
    
    public static final Resource S_MNCU = m_model.createResource( "http://www.geonames.org/ontology#S.MNCU" );
    
    public static final Resource S_MNDT = m_model.createResource( "http://www.geonames.org/ontology#S.MNDT" );
    
    public static final Resource S_MNFE = m_model.createResource( "http://www.geonames.org/ontology#S.MNFE" );
    
    public static final Resource S_MNMT = m_model.createResource( "http://www.geonames.org/ontology#S.MNMT" );
    
    public static final Resource S_MNN = m_model.createResource( "http://www.geonames.org/ontology#S.MNN" );
    
    public static final Resource S_MNNI = m_model.createResource( "http://www.geonames.org/ontology#S.MNNI" );
    
    public static final Resource S_MNPB = m_model.createResource( "http://www.geonames.org/ontology#S.MNPB" );
    
    public static final Resource S_MNPL = m_model.createResource( "http://www.geonames.org/ontology#S.MNPL" );
    
    public static final Resource S_MNQ = m_model.createResource( "http://www.geonames.org/ontology#S.MNQ" );
    
    public static final Resource S_MNQR = m_model.createResource( "http://www.geonames.org/ontology#S.MNQR" );
    
    public static final Resource S_MNSN = m_model.createResource( "http://www.geonames.org/ontology#S.MNSN" );
    
    public static final Resource S_MOLE = m_model.createResource( "http://www.geonames.org/ontology#S.MOLE" );
    
    public static final Resource S_MSQE = m_model.createResource( "http://www.geonames.org/ontology#S.MSQE" );
    
    public static final Resource S_MSSN = m_model.createResource( "http://www.geonames.org/ontology#S.MSSN" );
    
    public static final Resource S_MSSNQ = m_model.createResource( "http://www.geonames.org/ontology#S.MSSNQ" );
    
    public static final Resource S_MSTY = m_model.createResource( "http://www.geonames.org/ontology#S.MSTY" );
    
    public static final Resource S_MTRO = m_model.createResource( "http://www.geonames.org/ontology#S.MTRO" );
    
    public static final Resource S_MUS = m_model.createResource( "http://www.geonames.org/ontology#S.MUS" );
    
    public static final Resource S_NOV = m_model.createResource( "http://www.geonames.org/ontology#S.NOV" );
    
    public static final Resource S_NSY = m_model.createResource( "http://www.geonames.org/ontology#S.NSY" );
    
    public static final Resource S_OBPT = m_model.createResource( "http://www.geonames.org/ontology#S.OBPT" );
    
    public static final Resource S_OBS = m_model.createResource( "http://www.geonames.org/ontology#S.OBS" );
    
    public static final Resource S_OBSR = m_model.createResource( "http://www.geonames.org/ontology#S.OBSR" );
    
    public static final Resource S_OILJ = m_model.createResource( "http://www.geonames.org/ontology#S.OILJ" );
    
    public static final Resource S_OILQ = m_model.createResource( "http://www.geonames.org/ontology#S.OILQ" );
    
    public static final Resource S_OILR = m_model.createResource( "http://www.geonames.org/ontology#S.OILR" );
    
    public static final Resource S_OILT = m_model.createResource( "http://www.geonames.org/ontology#S.OILT" );
    
    public static final Resource S_OILW = m_model.createResource( "http://www.geonames.org/ontology#S.OILW" );
    
    public static final Resource S_OPRA = m_model.createResource( "http://www.geonames.org/ontology#S.OPRA" );
    
    public static final Resource S_PAL = m_model.createResource( "http://www.geonames.org/ontology#S.PAL" );
    
    public static final Resource S_PGDA = m_model.createResource( "http://www.geonames.org/ontology#S.PGDA" );
    
    public static final Resource S_PIER = m_model.createResource( "http://www.geonames.org/ontology#S.PIER" );
    
    public static final Resource S_PKLT = m_model.createResource( "http://www.geonames.org/ontology#S.PKLT" );
    
    public static final Resource S_PMPO = m_model.createResource( "http://www.geonames.org/ontology#S.PMPO" );
    
    public static final Resource S_PMPW = m_model.createResource( "http://www.geonames.org/ontology#S.PMPW" );
    
    public static final Resource S_PO = m_model.createResource( "http://www.geonames.org/ontology#S.PO" );
    
    public static final Resource S_PP = m_model.createResource( "http://www.geonames.org/ontology#S.PP" );
    
    public static final Resource S_PPQ = m_model.createResource( "http://www.geonames.org/ontology#S.PPQ" );
    
    public static final Resource S_PRKGT = m_model.createResource( "http://www.geonames.org/ontology#S.PRKGT" );
    
    public static final Resource S_PRKHQ = m_model.createResource( "http://www.geonames.org/ontology#S.PRKHQ" );
    
    public static final Resource S_PRN = m_model.createResource( "http://www.geonames.org/ontology#S.PRN" );
    
    public static final Resource S_PRNJ = m_model.createResource( "http://www.geonames.org/ontology#S.PRNJ" );
    
    public static final Resource S_PRNQ = m_model.createResource( "http://www.geonames.org/ontology#S.PRNQ" );
    
    public static final Resource S_PS = m_model.createResource( "http://www.geonames.org/ontology#S.PS" );
    
    public static final Resource S_PSH = m_model.createResource( "http://www.geonames.org/ontology#S.PSH" );
    
    public static final Resource S_PSTB = m_model.createResource( "http://www.geonames.org/ontology#S.PSTB" );
    
    public static final Resource S_PSTC = m_model.createResource( "http://www.geonames.org/ontology#S.PSTC" );
    
    public static final Resource S_PSTP = m_model.createResource( "http://www.geonames.org/ontology#S.PSTP" );
    
    public static final Resource S_PYR = m_model.createResource( "http://www.geonames.org/ontology#S.PYR" );
    
    public static final Resource S_PYRS = m_model.createResource( "http://www.geonames.org/ontology#S.PYRS" );
    
    public static final Resource S_QUAY = m_model.createResource( "http://www.geonames.org/ontology#S.QUAY" );
    
    public static final Resource S_RDCR = m_model.createResource( "http://www.geonames.org/ontology#S.RDCR" );
    
    public static final Resource S_RECG = m_model.createResource( "http://www.geonames.org/ontology#S.RECG" );
    
    public static final Resource S_RECR = m_model.createResource( "http://www.geonames.org/ontology#S.RECR" );
    
    public static final Resource S_REST = m_model.createResource( "http://www.geonames.org/ontology#S.REST" );
    
    public static final Resource S_RET = m_model.createResource( "http://www.geonames.org/ontology#S.RET" );
    
    public static final Resource S_RHSE = m_model.createResource( "http://www.geonames.org/ontology#S.RHSE" );
    
    public static final Resource S_RKRY = m_model.createResource( "http://www.geonames.org/ontology#S.RKRY" );
    
    public static final Resource S_RLG = m_model.createResource( "http://www.geonames.org/ontology#S.RLG" );
    
    public static final Resource S_RLGR = m_model.createResource( "http://www.geonames.org/ontology#S.RLGR" );
    
    public static final Resource S_RNCH = m_model.createResource( "http://www.geonames.org/ontology#S.RNCH" );
    
    public static final Resource S_RSD = m_model.createResource( "http://www.geonames.org/ontology#S.RSD" );
    
    public static final Resource S_RSGNL = m_model.createResource( "http://www.geonames.org/ontology#S.RSGNL" );
    
    public static final Resource S_RSRT = m_model.createResource( "http://www.geonames.org/ontology#S.RSRT" );
    
    public static final Resource S_RSTN = m_model.createResource( "http://www.geonames.org/ontology#S.RSTN" );
    
    public static final Resource S_RSTNQ = m_model.createResource( "http://www.geonames.org/ontology#S.RSTNQ" );
    
    public static final Resource S_RSTP = m_model.createResource( "http://www.geonames.org/ontology#S.RSTP" );
    
    public static final Resource S_RSTPQ = m_model.createResource( "http://www.geonames.org/ontology#S.RSTPQ" );
    
    public static final Resource S_RUIN = m_model.createResource( "http://www.geonames.org/ontology#S.RUIN" );
    
    public static final Resource S_SCH = m_model.createResource( "http://www.geonames.org/ontology#S.SCH" );
    
    public static final Resource S_SCHA = m_model.createResource( "http://www.geonames.org/ontology#S.SCHA" );
    
    public static final Resource S_SCHC = m_model.createResource( "http://www.geonames.org/ontology#S.SCHC" );
    
    public static final Resource S_SCHD = m_model.createResource( "http://www.geonames.org/ontology#S.SCHD" );
    
    public static final Resource S_SCHL = m_model.createResource( "http://www.geonames.org/ontology#S.SCHL" );
    
    public static final Resource S_SCHM = m_model.createResource( "http://www.geonames.org/ontology#S.SCHM" );
    
    public static final Resource S_SCHN = m_model.createResource( "http://www.geonames.org/ontology#S.SCHN" );
    
    public static final Resource S_SCHT = m_model.createResource( "http://www.geonames.org/ontology#S.SCHT" );
    
    public static final Resource S_SECP = m_model.createResource( "http://www.geonames.org/ontology#S.SECP" );
    
    public static final Resource S_SHPF = m_model.createResource( "http://www.geonames.org/ontology#S.SHPF" );
    
    public static final Resource S_SHRN = m_model.createResource( "http://www.geonames.org/ontology#S.SHRN" );
    
    public static final Resource S_SHSE = m_model.createResource( "http://www.geonames.org/ontology#S.SHSE" );
    
    public static final Resource S_SLCE = m_model.createResource( "http://www.geonames.org/ontology#S.SLCE" );
    
    public static final Resource S_SNTR = m_model.createResource( "http://www.geonames.org/ontology#S.SNTR" );
    
    public static final Resource S_SPA = m_model.createResource( "http://www.geonames.org/ontology#S.SPA" );
    
    public static final Resource S_SPLY = m_model.createResource( "http://www.geonames.org/ontology#S.SPLY" );
    
    public static final Resource S_SQR = m_model.createResource( "http://www.geonames.org/ontology#S.SQR" );
    
    public static final Resource S_STBL = m_model.createResource( "http://www.geonames.org/ontology#S.STBL" );
    
    public static final Resource S_STDM = m_model.createResource( "http://www.geonames.org/ontology#S.STDM" );
    
    public static final Resource S_STNB = m_model.createResource( "http://www.geonames.org/ontology#S.STNB" );
    
    public static final Resource S_STNC = m_model.createResource( "http://www.geonames.org/ontology#S.STNC" );
    
    public static final Resource S_STNE = m_model.createResource( "http://www.geonames.org/ontology#S.STNE" );
    
    public static final Resource S_STNF = m_model.createResource( "http://www.geonames.org/ontology#S.STNF" );
    
    public static final Resource S_STNI = m_model.createResource( "http://www.geonames.org/ontology#S.STNI" );
    
    public static final Resource S_STNM = m_model.createResource( "http://www.geonames.org/ontology#S.STNM" );
    
    public static final Resource S_STNR = m_model.createResource( "http://www.geonames.org/ontology#S.STNR" );
    
    public static final Resource S_STNS = m_model.createResource( "http://www.geonames.org/ontology#S.STNS" );
    
    public static final Resource S_STNW = m_model.createResource( "http://www.geonames.org/ontology#S.STNW" );
    
    public static final Resource S_STPS = m_model.createResource( "http://www.geonames.org/ontology#S.STPS" );
    
    public static final Resource S_SWT = m_model.createResource( "http://www.geonames.org/ontology#S.SWT" );
    
    public static final Resource S_THTR = m_model.createResource( "http://www.geonames.org/ontology#S.THTR" );
    
    public static final Resource S_TMB = m_model.createResource( "http://www.geonames.org/ontology#S.TMB" );
    
    public static final Resource S_TMPL = m_model.createResource( "http://www.geonames.org/ontology#S.TMPL" );
    
    public static final Resource S_TNKD = m_model.createResource( "http://www.geonames.org/ontology#S.TNKD" );
    
    public static final Resource S_TOWR = m_model.createResource( "http://www.geonames.org/ontology#S.TOWR" );
    
    public static final Resource S_TRANT = m_model.createResource( "http://www.geonames.org/ontology#S.TRANT" );
    
    public static final Resource S_TRIG = m_model.createResource( "http://www.geonames.org/ontology#S.TRIG" );
    
    public static final Resource S_TRMO = m_model.createResource( "http://www.geonames.org/ontology#S.TRMO" );
    
    public static final Resource S_TWO = m_model.createResource( "http://www.geonames.org/ontology#S.TWO" );
    
    public static final Resource S_UNIO = m_model.createResource( "http://www.geonames.org/ontology#S.UNIO" );
    
    public static final Resource S_UNIP = m_model.createResource( "http://www.geonames.org/ontology#S.UNIP" );
    
    public static final Resource S_UNIV = m_model.createResource( "http://www.geonames.org/ontology#S.UNIV" );
    
    public static final Resource S_USGE = m_model.createResource( "http://www.geonames.org/ontology#S.USGE" );
    
    public static final Resource S_VETF = m_model.createResource( "http://www.geonames.org/ontology#S.VETF" );
    
    public static final Resource S_WALL = m_model.createResource( "http://www.geonames.org/ontology#S.WALL" );
    
    public static final Resource S_WALLA = m_model.createResource( "http://www.geonames.org/ontology#S.WALLA" );
    
    public static final Resource S_WEIR = m_model.createResource( "http://www.geonames.org/ontology#S.WEIR" );
    
    public static final Resource S_WHRF = m_model.createResource( "http://www.geonames.org/ontology#S.WHRF" );
    
    public static final Resource S_WRCK = m_model.createResource( "http://www.geonames.org/ontology#S.WRCK" );
    
    public static final Resource S_WTRW = m_model.createResource( "http://www.geonames.org/ontology#S.WTRW" );
    
    public static final Resource S_ZNF = m_model.createResource( "http://www.geonames.org/ontology#S.ZNF" );
    
    public static final Resource S_ZOO = m_model.createResource( "http://www.geonames.org/ontology#S.ZOO" );
    
    /** <p>mountain, hill, rock, ...</p> */
    public static final Resource T = m_model.createResource( "http://www.geonames.org/ontology#T" );
    
    public static final Resource T_ASPH = m_model.createResource( "http://www.geonames.org/ontology#T.ASPH" );
    
    public static final Resource T_ATOL = m_model.createResource( "http://www.geonames.org/ontology#T.ATOL" );
    
    public static final Resource T_BAR = m_model.createResource( "http://www.geonames.org/ontology#T.BAR" );
    
    public static final Resource T_BCH = m_model.createResource( "http://www.geonames.org/ontology#T.BCH" );
    
    public static final Resource T_BCHS = m_model.createResource( "http://www.geonames.org/ontology#T.BCHS" );
    
    public static final Resource T_BDLD = m_model.createResource( "http://www.geonames.org/ontology#T.BDLD" );
    
    public static final Resource T_BLDR = m_model.createResource( "http://www.geonames.org/ontology#T.BLDR" );
    
    public static final Resource T_BLHL = m_model.createResource( "http://www.geonames.org/ontology#T.BLHL" );
    
    public static final Resource T_BLOW = m_model.createResource( "http://www.geonames.org/ontology#T.BLOW" );
    
    public static final Resource T_BNCH = m_model.createResource( "http://www.geonames.org/ontology#T.BNCH" );
    
    public static final Resource T_BUTE = m_model.createResource( "http://www.geonames.org/ontology#T.BUTE" );
    
    public static final Resource T_CAPE = m_model.createResource( "http://www.geonames.org/ontology#T.CAPE" );
    
    public static final Resource T_CFT = m_model.createResource( "http://www.geonames.org/ontology#T.CFT" );
    
    public static final Resource T_CLDA = m_model.createResource( "http://www.geonames.org/ontology#T.CLDA" );
    
    public static final Resource T_CLF = m_model.createResource( "http://www.geonames.org/ontology#T.CLF" );
    
    public static final Resource T_CNYN = m_model.createResource( "http://www.geonames.org/ontology#T.CNYN" );
    
    public static final Resource T_CONE = m_model.createResource( "http://www.geonames.org/ontology#T.CONE" );
    
    public static final Resource T_CRDR = m_model.createResource( "http://www.geonames.org/ontology#T.CRDR" );
    
    public static final Resource T_CRQ = m_model.createResource( "http://www.geonames.org/ontology#T.CRQ" );
    
    public static final Resource T_CRQS = m_model.createResource( "http://www.geonames.org/ontology#T.CRQS" );
    
    public static final Resource T_CRTR = m_model.createResource( "http://www.geonames.org/ontology#T.CRTR" );
    
    public static final Resource T_CUET = m_model.createResource( "http://www.geonames.org/ontology#T.CUET" );
    
    public static final Resource T_DLTA = m_model.createResource( "http://www.geonames.org/ontology#T.DLTA" );
    
    public static final Resource T_DPR = m_model.createResource( "http://www.geonames.org/ontology#T.DPR" );
    
    public static final Resource T_DSRT = m_model.createResource( "http://www.geonames.org/ontology#T.DSRT" );
    
    public static final Resource T_DUNE = m_model.createResource( "http://www.geonames.org/ontology#T.DUNE" );
    
    public static final Resource T_DVD = m_model.createResource( "http://www.geonames.org/ontology#T.DVD" );
    
    public static final Resource T_ERG = m_model.createResource( "http://www.geonames.org/ontology#T.ERG" );
    
    public static final Resource T_FAN = m_model.createResource( "http://www.geonames.org/ontology#T.FAN" );
    
    public static final Resource T_FORD = m_model.createResource( "http://www.geonames.org/ontology#T.FORD" );
    
    public static final Resource T_FSR = m_model.createResource( "http://www.geonames.org/ontology#T.FSR" );
    
    public static final Resource T_GAP = m_model.createResource( "http://www.geonames.org/ontology#T.GAP" );
    
    public static final Resource T_GRGE = m_model.createResource( "http://www.geonames.org/ontology#T.GRGE" );
    
    public static final Resource T_HDLD = m_model.createResource( "http://www.geonames.org/ontology#T.HDLD" );
    
    public static final Resource T_HLL = m_model.createResource( "http://www.geonames.org/ontology#T.HLL" );
    
    public static final Resource T_HLLS = m_model.createResource( "http://www.geonames.org/ontology#T.HLLS" );
    
    public static final Resource T_HMCK = m_model.createResource( "http://www.geonames.org/ontology#T.HMCK" );
    
    public static final Resource T_HMDA = m_model.createResource( "http://www.geonames.org/ontology#T.HMDA" );
    
    public static final Resource T_INTF = m_model.createResource( "http://www.geonames.org/ontology#T.INTF" );
    
    public static final Resource T_ISL = m_model.createResource( "http://www.geonames.org/ontology#T.ISL" );
    
    public static final Resource T_ISLET = m_model.createResource( "http://www.geonames.org/ontology#T.ISLET" );
    
    public static final Resource T_ISLF = m_model.createResource( "http://www.geonames.org/ontology#T.ISLF" );
    
    public static final Resource T_ISLM = m_model.createResource( "http://www.geonames.org/ontology#T.ISLM" );
    
    public static final Resource T_ISLS = m_model.createResource( "http://www.geonames.org/ontology#T.ISLS" );
    
    public static final Resource T_ISLT = m_model.createResource( "http://www.geonames.org/ontology#T.ISLT" );
    
    public static final Resource T_ISLX = m_model.createResource( "http://www.geonames.org/ontology#T.ISLX" );
    
    public static final Resource T_ISTH = m_model.createResource( "http://www.geonames.org/ontology#T.ISTH" );
    
    public static final Resource T_KRST = m_model.createResource( "http://www.geonames.org/ontology#T.KRST" );
    
    public static final Resource T_LAVA = m_model.createResource( "http://www.geonames.org/ontology#T.LAVA" );
    
    public static final Resource T_LEV = m_model.createResource( "http://www.geonames.org/ontology#T.LEV" );
    
    public static final Resource T_MESA = m_model.createResource( "http://www.geonames.org/ontology#T.MESA" );
    
    public static final Resource T_MND = m_model.createResource( "http://www.geonames.org/ontology#T.MND" );
    
    public static final Resource T_MRN = m_model.createResource( "http://www.geonames.org/ontology#T.MRN" );
    
    public static final Resource T_MT = m_model.createResource( "http://www.geonames.org/ontology#T.MT" );
    
    public static final Resource T_MTS = m_model.createResource( "http://www.geonames.org/ontology#T.MTS" );
    
    public static final Resource T_NKM = m_model.createResource( "http://www.geonames.org/ontology#T.NKM" );
    
    public static final Resource T_NTK = m_model.createResource( "http://www.geonames.org/ontology#T.NTK" );
    
    public static final Resource T_NTKS = m_model.createResource( "http://www.geonames.org/ontology#T.NTKS" );
    
    public static final Resource T_PAN = m_model.createResource( "http://www.geonames.org/ontology#T.PAN" );
    
    public static final Resource T_PANS = m_model.createResource( "http://www.geonames.org/ontology#T.PANS" );
    
    public static final Resource T_PASS = m_model.createResource( "http://www.geonames.org/ontology#T.PASS" );
    
    public static final Resource T_PEN = m_model.createResource( "http://www.geonames.org/ontology#T.PEN" );
    
    public static final Resource T_PENX = m_model.createResource( "http://www.geonames.org/ontology#T.PENX" );
    
    public static final Resource T_PK = m_model.createResource( "http://www.geonames.org/ontology#T.PK" );
    
    public static final Resource T_PKS = m_model.createResource( "http://www.geonames.org/ontology#T.PKS" );
    
    public static final Resource T_PLAT = m_model.createResource( "http://www.geonames.org/ontology#T.PLAT" );
    
    public static final Resource T_PLATX = m_model.createResource( "http://www.geonames.org/ontology#T.PLATX" );
    
    public static final Resource T_PLDR = m_model.createResource( "http://www.geonames.org/ontology#T.PLDR" );
    
    public static final Resource T_PLN = m_model.createResource( "http://www.geonames.org/ontology#T.PLN" );
    
    public static final Resource T_PLNX = m_model.createResource( "http://www.geonames.org/ontology#T.PLNX" );
    
    public static final Resource T_PROM = m_model.createResource( "http://www.geonames.org/ontology#T.PROM" );
    
    public static final Resource T_PT = m_model.createResource( "http://www.geonames.org/ontology#T.PT" );
    
    public static final Resource T_PTS = m_model.createResource( "http://www.geonames.org/ontology#T.PTS" );
    
    public static final Resource T_RDGB = m_model.createResource( "http://www.geonames.org/ontology#T.RDGB" );
    
    public static final Resource T_RDGE = m_model.createResource( "http://www.geonames.org/ontology#T.RDGE" );
    
    public static final Resource T_REG = m_model.createResource( "http://www.geonames.org/ontology#T.REG" );
    
    public static final Resource T_RK = m_model.createResource( "http://www.geonames.org/ontology#T.RK" );
    
    public static final Resource T_RKFL = m_model.createResource( "http://www.geonames.org/ontology#T.RKFL" );
    
    public static final Resource T_RKS = m_model.createResource( "http://www.geonames.org/ontology#T.RKS" );
    
    public static final Resource T_SAND = m_model.createResource( "http://www.geonames.org/ontology#T.SAND" );
    
    public static final Resource T_SBED = m_model.createResource( "http://www.geonames.org/ontology#T.SBED" );
    
    public static final Resource T_SCRP = m_model.createResource( "http://www.geonames.org/ontology#T.SCRP" );
    
    public static final Resource T_SDL = m_model.createResource( "http://www.geonames.org/ontology#T.SDL" );
    
    public static final Resource T_SHOR = m_model.createResource( "http://www.geonames.org/ontology#T.SHOR" );
    
    public static final Resource T_SINK = m_model.createResource( "http://www.geonames.org/ontology#T.SINK" );
    
    public static final Resource T_SLID = m_model.createResource( "http://www.geonames.org/ontology#T.SLID" );
    
    public static final Resource T_SLP = m_model.createResource( "http://www.geonames.org/ontology#T.SLP" );
    
    public static final Resource T_SPIT = m_model.createResource( "http://www.geonames.org/ontology#T.SPIT" );
    
    public static final Resource T_SPUR = m_model.createResource( "http://www.geonames.org/ontology#T.SPUR" );
    
    public static final Resource T_TAL = m_model.createResource( "http://www.geonames.org/ontology#T.TAL" );
    
    public static final Resource T_TRGD = m_model.createResource( "http://www.geonames.org/ontology#T.TRGD" );
    
    public static final Resource T_TRR = m_model.createResource( "http://www.geonames.org/ontology#T.TRR" );
    
    public static final Resource T_UPLD = m_model.createResource( "http://www.geonames.org/ontology#T.UPLD" );
    
    public static final Resource T_VAL = m_model.createResource( "http://www.geonames.org/ontology#T.VAL" );
    
    public static final Resource T_VALG = m_model.createResource( "http://www.geonames.org/ontology#T.VALG" );
    
    public static final Resource T_VALS = m_model.createResource( "http://www.geonames.org/ontology#T.VALS" );
    
    public static final Resource T_VALX = m_model.createResource( "http://www.geonames.org/ontology#T.VALX" );
    
    public static final Resource T_VLC = m_model.createResource( "http://www.geonames.org/ontology#T.VLC" );
    
    /** <p>undersea</p> */
    public static final Resource U = m_model.createResource( "http://www.geonames.org/ontology#U" );
    
    public static final Resource U_APNU = m_model.createResource( "http://www.geonames.org/ontology#U.APNU" );
    
    public static final Resource U_ARCU = m_model.createResource( "http://www.geonames.org/ontology#U.ARCU" );
    
    public static final Resource U_ARRU = m_model.createResource( "http://www.geonames.org/ontology#U.ARRU" );
    
    public static final Resource U_BDLU = m_model.createResource( "http://www.geonames.org/ontology#U.BDLU" );
    
    public static final Resource U_BKSU = m_model.createResource( "http://www.geonames.org/ontology#U.BKSU" );
    
    public static final Resource U_BNCU = m_model.createResource( "http://www.geonames.org/ontology#U.BNCU" );
    
    public static final Resource U_BNKU = m_model.createResource( "http://www.geonames.org/ontology#U.BNKU" );
    
    public static final Resource U_BSNU = m_model.createResource( "http://www.geonames.org/ontology#U.BSNU" );
    
    public static final Resource U_CDAU = m_model.createResource( "http://www.geonames.org/ontology#U.CDAU" );
    
    public static final Resource U_CNSU = m_model.createResource( "http://www.geonames.org/ontology#U.CNSU" );
    
    public static final Resource U_CNYU = m_model.createResource( "http://www.geonames.org/ontology#U.CNYU" );
    
    public static final Resource U_CRSU = m_model.createResource( "http://www.geonames.org/ontology#U.CRSU" );
    
    public static final Resource U_DEPU = m_model.createResource( "http://www.geonames.org/ontology#U.DEPU" );
    
    public static final Resource U_EDGU = m_model.createResource( "http://www.geonames.org/ontology#U.EDGU" );
    
    public static final Resource U_ESCU = m_model.createResource( "http://www.geonames.org/ontology#U.ESCU" );
    
    public static final Resource U_FANU = m_model.createResource( "http://www.geonames.org/ontology#U.FANU" );
    
    public static final Resource U_FLTU = m_model.createResource( "http://www.geonames.org/ontology#U.FLTU" );
    
    public static final Resource U_FRKU = m_model.createResource( "http://www.geonames.org/ontology#U.FRKU" );
    
    public static final Resource U_FRSU = m_model.createResource( "http://www.geonames.org/ontology#U.FRSU" );
    
    public static final Resource U_FRZU = m_model.createResource( "http://www.geonames.org/ontology#U.FRZU" );
    
    public static final Resource U_FURU = m_model.createResource( "http://www.geonames.org/ontology#U.FURU" );
    
    public static final Resource U_GAPU = m_model.createResource( "http://www.geonames.org/ontology#U.GAPU" );
    
    public static final Resource U_GLYU = m_model.createResource( "http://www.geonames.org/ontology#U.GLYU" );
    
    public static final Resource U_HLLU = m_model.createResource( "http://www.geonames.org/ontology#U.HLLU" );
    
    public static final Resource U_HLSU = m_model.createResource( "http://www.geonames.org/ontology#U.HLSU" );
    
    public static final Resource U_HOLU = m_model.createResource( "http://www.geonames.org/ontology#U.HOLU" );
    
    public static final Resource U_KNLU = m_model.createResource( "http://www.geonames.org/ontology#U.KNLU" );
    
    public static final Resource U_KNSU = m_model.createResource( "http://www.geonames.org/ontology#U.KNSU" );
    
    public static final Resource U_LDGU = m_model.createResource( "http://www.geonames.org/ontology#U.LDGU" );
    
    public static final Resource U_LEVU = m_model.createResource( "http://www.geonames.org/ontology#U.LEVU" );
    
    public static final Resource U_MDVU = m_model.createResource( "http://www.geonames.org/ontology#U.MDVU" );
    
    public static final Resource U_MESU = m_model.createResource( "http://www.geonames.org/ontology#U.MESU" );
    
    public static final Resource U_MNDU = m_model.createResource( "http://www.geonames.org/ontology#U.MNDU" );
    
    public static final Resource U_MOTU = m_model.createResource( "http://www.geonames.org/ontology#U.MOTU" );
    
    public static final Resource U_MTSU = m_model.createResource( "http://www.geonames.org/ontology#U.MTSU" );
    
    public static final Resource U_MTU = m_model.createResource( "http://www.geonames.org/ontology#U.MTU" );
    
    public static final Resource U_PKSU = m_model.createResource( "http://www.geonames.org/ontology#U.PKSU" );
    
    public static final Resource U_PKU = m_model.createResource( "http://www.geonames.org/ontology#U.PKU" );
    
    public static final Resource U_PLFU = m_model.createResource( "http://www.geonames.org/ontology#U.PLFU" );
    
    public static final Resource U_PLNU = m_model.createResource( "http://www.geonames.org/ontology#U.PLNU" );
    
    public static final Resource U_PLTU = m_model.createResource( "http://www.geonames.org/ontology#U.PLTU" );
    
    public static final Resource U_PNLU = m_model.createResource( "http://www.geonames.org/ontology#U.PNLU" );
    
    public static final Resource U_PRVU = m_model.createResource( "http://www.geonames.org/ontology#U.PRVU" );
    
    public static final Resource U_RAVU = m_model.createResource( "http://www.geonames.org/ontology#U.RAVU" );
    
    public static final Resource U_RDGU = m_model.createResource( "http://www.geonames.org/ontology#U.RDGU" );
    
    public static final Resource U_RDSU = m_model.createResource( "http://www.geonames.org/ontology#U.RDSU" );
    
    public static final Resource U_RFSU = m_model.createResource( "http://www.geonames.org/ontology#U.RFSU" );
    
    public static final Resource U_RFU = m_model.createResource( "http://www.geonames.org/ontology#U.RFU" );
    
    public static final Resource U_RISU = m_model.createResource( "http://www.geonames.org/ontology#U.RISU" );
    
    public static final Resource U_RMPU = m_model.createResource( "http://www.geonames.org/ontology#U.RMPU" );
    
    public static final Resource U_RNGU = m_model.createResource( "http://www.geonames.org/ontology#U.RNGU" );
    
    public static final Resource U_SCNU = m_model.createResource( "http://www.geonames.org/ontology#U.SCNU" );
    
    public static final Resource U_SCSU = m_model.createResource( "http://www.geonames.org/ontology#U.SCSU" );
    
    public static final Resource U_SDLU = m_model.createResource( "http://www.geonames.org/ontology#U.SDLU" );
    
    public static final Resource U_SHFU = m_model.createResource( "http://www.geonames.org/ontology#U.SHFU" );
    
    public static final Resource U_SHLU = m_model.createResource( "http://www.geonames.org/ontology#U.SHLU" );
    
    public static final Resource U_SHSU = m_model.createResource( "http://www.geonames.org/ontology#U.SHSU" );
    
    public static final Resource U_SHVU = m_model.createResource( "http://www.geonames.org/ontology#U.SHVU" );
    
    public static final Resource U_SILU = m_model.createResource( "http://www.geonames.org/ontology#U.SILU" );
    
    public static final Resource U_SLPU = m_model.createResource( "http://www.geonames.org/ontology#U.SLPU" );
    
    public static final Resource U_SMSU = m_model.createResource( "http://www.geonames.org/ontology#U.SMSU" );
    
    public static final Resource U_SMU = m_model.createResource( "http://www.geonames.org/ontology#U.SMU" );
    
    public static final Resource U_SPRU = m_model.createResource( "http://www.geonames.org/ontology#U.SPRU" );
    
    public static final Resource U_TERU = m_model.createResource( "http://www.geonames.org/ontology#U.TERU" );
    
    public static final Resource U_TMSU = m_model.createResource( "http://www.geonames.org/ontology#U.TMSU" );
    
    public static final Resource U_TMTU = m_model.createResource( "http://www.geonames.org/ontology#U.TMTU" );
    
    public static final Resource U_TNGU = m_model.createResource( "http://www.geonames.org/ontology#U.TNGU" );
    
    public static final Resource U_TRGU = m_model.createResource( "http://www.geonames.org/ontology#U.TRGU" );
    
    public static final Resource U_TRNU = m_model.createResource( "http://www.geonames.org/ontology#U.TRNU" );
    
    public static final Resource U_VALU = m_model.createResource( "http://www.geonames.org/ontology#U.VALU" );
    
    public static final Resource U_VLSU = m_model.createResource( "http://www.geonames.org/ontology#U.VLSU" );
    
    /** <p>forest, heath, ...</p> */
    public static final Resource V = m_model.createResource( "http://www.geonames.org/ontology#V" );
    
    public static final Resource V_BUSH = m_model.createResource( "http://www.geonames.org/ontology#V.BUSH" );
    
    public static final Resource V_CULT = m_model.createResource( "http://www.geonames.org/ontology#V.CULT" );
    
    public static final Resource V_FRST = m_model.createResource( "http://www.geonames.org/ontology#V.FRST" );
    
    public static final Resource V_FRSTF = m_model.createResource( "http://www.geonames.org/ontology#V.FRSTF" );
    
    public static final Resource V_GRSLD = m_model.createResource( "http://www.geonames.org/ontology#V.GRSLD" );
    
    public static final Resource V_GRVC = m_model.createResource( "http://www.geonames.org/ontology#V.GRVC" );
    
    public static final Resource V_GRVO = m_model.createResource( "http://www.geonames.org/ontology#V.GRVO" );
    
    public static final Resource V_GRVP = m_model.createResource( "http://www.geonames.org/ontology#V.GRVP" );
    
    public static final Resource V_GRVPN = m_model.createResource( "http://www.geonames.org/ontology#V.GRVPN" );
    
    public static final Resource V_HTH = m_model.createResource( "http://www.geonames.org/ontology#V.HTH" );
    
    public static final Resource V_MDW = m_model.createResource( "http://www.geonames.org/ontology#V.MDW" );
    
    public static final Resource V_OCH = m_model.createResource( "http://www.geonames.org/ontology#V.OCH" );
    
    public static final Resource V_SCRB = m_model.createResource( "http://www.geonames.org/ontology#V.SCRB" );
    
    public static final Resource V_TREE = m_model.createResource( "http://www.geonames.org/ontology#V.TREE" );
    
    public static final Resource V_TUND = m_model.createResource( "http://www.geonames.org/ontology#V.TUND" );
    
    public static final Resource V_VIN = m_model.createResource( "http://www.geonames.org/ontology#V.VIN" );
    
    public static final Resource V_VINS = m_model.createResource( "http://www.geonames.org/ontology#V.VINS" );
    
}
