//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.28 at 05:27:30 μμ EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:openiot:osdspec:xsd:1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openiot.commons.osdspec.model;
