//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 12:49:31 
//


package org.openiot.commons.osdspec.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.openiot.eu/osdspec}QuerySchedule"/>
 *         &lt;element name="trigger" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="initialRecordTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="reportIfEmpty" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "querySchedule",
    "trigger",
    "initialRecordTime",
    "reportIfEmpty"
})
@XmlRootElement(name = "queryControls")
public class QueryControls {

    @XmlElement(name = "QuerySchedule", required = true)
    protected QuerySchedule querySchedule;
    @XmlSchemaType(name = "anyURI")
    protected String trigger;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar initialRecordTime;
    protected boolean reportIfEmpty;

    /**
     * Gets the value of the querySchedule property.
     * 
     * @return
     *     possible object is
     *     {@link QuerySchedule }
     *     
     */
    public QuerySchedule getQuerySchedule() {
        return querySchedule;
    }

    /**
     * Sets the value of the querySchedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuerySchedule }
     *     
     */
    public void setQuerySchedule(QuerySchedule value) {
        this.querySchedule = value;
    }

    /**
     * Gets the value of the trigger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrigger() {
        return trigger;
    }

    /**
     * Sets the value of the trigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrigger(String value) {
        this.trigger = value;
    }

    /**
     * Gets the value of the initialRecordTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInitialRecordTime() {
        return initialRecordTime;
    }

    /**
     * Sets the value of the initialRecordTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInitialRecordTime(XMLGregorianCalendar value) {
        this.initialRecordTime = value;
    }

    /**
     * Gets the value of the reportIfEmpty property.
     * 
     */
    public boolean isReportIfEmpty() {
        return reportIfEmpty;
    }

    /**
     * Sets the value of the reportIfEmpty property.
     * 
     */
    public void setReportIfEmpty(boolean value) {
        this.reportIfEmpty = value;
    }

}
