
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 10:19:53 �� EEST 
//


package org.openiot.commons.osdspec.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openiot.commons.osdspec.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openiot.commons.osdspec.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceName }
     * 
     */
    public ServiceName createServiceName() {
        return new ServiceName();
    }

    /**
     * Create an instance of {@link ServiceDescription }
     * 
     */
    public ServiceDescription createServiceDescription() {
        return new ServiceDescription();
    }

    /**
     * Create an instance of {@link QueryRequest }
     * 
     */
    public QueryRequest createQueryRequest() {
        return new QueryRequest();
    }

    /**
     * Create an instance of {@link ServiceID }
     * 
     */
    public ServiceID createServiceID() {
        return new ServiceID();
    }

    /**
     * Create an instance of {@link Widget }
     * 
     */
    public Widget createWidget() {
        return new Widget();
    }

    /**
     * Create an instance of {@link QuerySchedule }
     * 
     */
    public QuerySchedule createQuerySchedule() {
        return new QuerySchedule();
    }

    /**
     * Create an instance of {@link OSDSpec }
     * 
     */
    public OSDSpec createOSDSpec() {
        return new OSDSpec();
    }

    /**
     * Create an instance of {@link RequestPresentation }
     * 
     */
    public RequestPresentation createRequestPresentation() {
        return new RequestPresentation();
    }

    /**
     * Create an instance of {@link PresentationAttr }
     * 
     */
    public PresentationAttr createPresentationAttr() {
        return new PresentationAttr();
    }

    /**
     * Create an instance of {@link DescriptiveID }
     * 
     */
    public DescriptiveID createDescriptiveID() {
        return new DescriptiveID();
    }

    /**
     * Create an instance of {@link QueryControls }
     * 
     */
    public QueryControls createQueryControls() {
        return new QueryControls();
    }

    /**
     * Create an instance of {@link OSMO }
     * 
     */
    public OSMO createOSMO() {
        return new OSMO();
    }

}
