
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.11 at 10:19:53 �� EEST 
//


package org.openiot.commons.osdspec.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}descriptiveID"/>
 *         &lt;element ref="{}queryControls"/>
 *         &lt;element ref="{}requestPresentation"/>
 *         &lt;element ref="{}query-request"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "descriptiveID",
    "queryControls",
    "requestPresentation",
    "queryRequest"
})
@XmlRootElement(name = "OSMO")
public class OSMO {

    @XmlElement(required = true)
    protected DescriptiveID descriptiveID;
    @XmlElement(required = true)
    protected QueryControls queryControls;
    @XmlElement(required = true)
    protected RequestPresentation requestPresentation;
    @XmlElement(name = "query-request", required = true)
    protected QueryRequest queryRequest;

    /**
     * Gets the value of the descriptiveID property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptiveID }
     *     
     */
    public DescriptiveID getDescriptiveID() {
        return descriptiveID;
    }

    /**
     * Sets the value of the descriptiveID property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptiveID }
     *     
     */
    public void setDescriptiveID(DescriptiveID value) {
        this.descriptiveID = value;
    }

    /**
     * Gets the value of the queryControls property.
     * 
     * @return
     *     possible object is
     *     {@link QueryControls }
     *     
     */
    public QueryControls getQueryControls() {
        return queryControls;
    }

    /**
     * Sets the value of the queryControls property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryControls }
     *     
     */
    public void setQueryControls(QueryControls value) {
        this.queryControls = value;
    }

    /**
     * Gets the value of the requestPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link RequestPresentation }
     *     
     */
    public RequestPresentation getRequestPresentation() {
        return requestPresentation;
    }

    /**
     * Sets the value of the requestPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestPresentation }
     *     
     */
    public void setRequestPresentation(RequestPresentation value) {
        this.requestPresentation = value;
    }

    /**
     * Gets the value of the queryRequest property.
     * 
     * @return
     *     possible object is
     *     {@link QueryRequest }
     *     
     */
    public QueryRequest getQueryRequest() {
        return queryRequest;
    }

    /**
     * Sets the value of the queryRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryRequest }
     *     
     */
    public void setQueryRequest(QueryRequest value) {
        this.queryRequest = value;
    }

}
