//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.08 at 04:21:47 
//


package org.openiot.commons.sdum.appusagereport.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}sensorUsed" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}dataVolume" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sensorUsed",
    "dataVolume"
})
@XmlRootElement(name = "ServiceUsage")
public class ServiceUsage {

    @XmlElement(required = true)
    protected List<SensorUsed> sensorUsed;
    protected DataVolume dataVolume;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anyURI")
    protected String id;

    /**
     * Gets the value of the sensorUsed property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sensorUsed property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSensorUsed().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SensorUsed }
     * 
     * 
     */
    public List<SensorUsed> getSensorUsed() {
        if (sensorUsed == null) {
            sensorUsed = new ArrayList<SensorUsed>();
        }
        return this.sensorUsed;
    }

    /**
     * Gets the value of the dataVolume property.
     * 
     * @return
     *     possible object is
     *     {@link DataVolume }
     *     
     */
    public DataVolume getDataVolume() {
        return dataVolume;
    }

    /**
     * Sets the value of the dataVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataVolume }
     *     
     */
    public void setDataVolume(DataVolume value) {
        this.dataVolume = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
