//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.30 at 07:14:34 μμ EEST 
//


package org.openiot.commons.sdum.appusagereport.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element ref="{}sensorInfo"/>
 *         &lt;/sequence>
 *         &lt;element ref="{}dataVolume" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sensorInfo",
    "dataVolume"
})
@XmlRootElement(name = "ServiceUsage")
public class ServiceUsage {

    @XmlElement(required = true)
    protected SensorInfo sensorInfo;
    protected DataVolume dataVolume;
    @XmlAttribute(name = "id")
    @XmlSchemaType(name = "anyURI")
    protected String id;

    /**
     * Gets the value of the sensorInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SensorInfo }
     *     
     */
    public SensorInfo getSensorInfo() {
        return sensorInfo;
    }

    /**
     * Sets the value of the sensorInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SensorInfo }
     *     
     */
    public void setSensorInfo(SensorInfo value) {
        this.sensorInfo = value;
    }

    /**
     * Gets the value of the dataVolume property.
     * 
     * @return
     *     possible object is
     *     {@link DataVolume }
     *     
     */
    public DataVolume getDataVolume() {
        return dataVolume;
    }

    /**
     * Sets the value of the dataVolume property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataVolume }
     *     
     */
    public void setDataVolume(DataVolume value) {
        this.dataVolume = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
