//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.25 at 12:49:31 
//


package org.openiot.commons.sparql.protocoltypes.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openiot.commons.sparql.protocoltypes.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FaultDetails_QNAME = new QName("http://www.w3.org/2007/SPARQL/protocol-types#", "fault-details");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openiot.commons.sparql.protocoltypes.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryRequestRefused }
     * 
     */
    public QueryRequestRefused createQueryRequestRefused() {
        return new QueryRequestRefused();
    }

    /**
     * Create an instance of {@link QueryRequest }
     * 
     */
    public QueryRequest createQueryRequest() {
        return new QueryRequest();
    }

    /**
     * Create an instance of {@link QueryResult }
     * 
     */
    public QueryResult createQueryResult() {
        return new QueryResult();
    }

    /**
     * Create an instance of {@link MalformedQuery }
     * 
     */
    public MalformedQuery createMalformedQuery() {
        return new MalformedQuery();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2007/SPARQL/protocol-types#", name = "fault-details")
    public JAXBElement<String> createFaultDetails(String value) {
        return new JAXBElement<String>(_FaultDetails_QNAME, String.class, null, value);
    }

}
