//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.13 at 04:10:11 
//


package org.openiot.commons.sdum.serviceresultset.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openiot.commons.sdum.serviceresultset.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openiot.commons.sdum.serviceresultset.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestPresentation }
     * 
     */
    public RequestPresentation createRequestPresentation() {
        return new RequestPresentation();
    }

    /**
     * Create an instance of {@link Widget }
     * 
     */
    public Widget createWidget() {
        return new Widget();
    }

    /**
     * Create an instance of {@link SdumServiceResultSet }
     * 
     */
    public SdumServiceResultSet createSdumServiceResultSet() {
        return new SdumServiceResultSet();
    }

    /**
     * Create an instance of {@link PresentationAttr }
     * 
     */
    public PresentationAttr createPresentationAttr() {
        return new PresentationAttr();
    }

}
