//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 02:02:34 рм EEST 
//


package org.openiot.commons.sdum.serviceresultset.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openiot.commons.sdum.serviceresultset.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SdumServiceResultSet_QNAME = new QName("urn:openiot:sdum:serviceresultset:xsd:1", "SdumServiceResultSet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openiot.commons.sdum.serviceresultset.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestPresentation }
     * 
     */
    public RequestPresentation createRequestPresentation() {
        return new RequestPresentation();
    }

    /**
     * Create an instance of {@link SdumServiceResultSet }
     * 
     */
    public SdumServiceResultSet createSdumServiceResultSet() {
        return new SdumServiceResultSet();
    }

    /**
     * Create an instance of {@link Widget }
     * 
     */
    public Widget createWidget() {
        return new Widget();
    }

    /**
     * Create an instance of {@link PresentationAttr }
     * 
     */
    public PresentationAttr createPresentationAttr() {
        return new PresentationAttr();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SdumServiceResultSet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:openiot:sdum:serviceresultset:xsd:1", name = "SdumServiceResultSet")
    public JAXBElement<SdumServiceResultSet> createSdumServiceResultSet(SdumServiceResultSet value) {
        return new JAXBElement<SdumServiceResultSet>(_SdumServiceResultSet_QNAME, SdumServiceResultSet.class, null, value);
    }

}
