//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.13 at 04:10:11 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:openiot:sdum:serviceresultset:xsd:1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.openiot.commons.sdum.serviceresultset.model;
