//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.27 at 02:02:34 рм EEST 
//


package org.openiot.commons.sdum.serviceresultset.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.openiot.commons.sparql.protocoltypes.model.QueryResult;


/**
 * <p>Java class for SdumServiceResultSet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SdumServiceResultSet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:openiot:sdum:serviceresultset:xsd:1}requestPresentation"/>
 *         &lt;element ref="{http://www.w3.org/2007/SPARQL/protocol-types#}query-result"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SdumServiceResultSet", propOrder = {
    "requestPresentation",
    "queryResult"
})
public class SdumServiceResultSet {

    @XmlElement(required = true)
    protected RequestPresentation requestPresentation;
    @XmlElement(name = "query-result", namespace = "http://www.w3.org/2007/SPARQL/protocol-types#", required = true)
    protected QueryResult queryResult;

    /**
     * Gets the value of the requestPresentation property.
     * 
     * @return
     *     possible object is
     *     {@link RequestPresentation }
     *     
     */
    public RequestPresentation getRequestPresentation() {
        return requestPresentation;
    }

    /**
     * Sets the value of the requestPresentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestPresentation }
     *     
     */
    public void setRequestPresentation(RequestPresentation value) {
        this.requestPresentation = value;
    }

    /**
     * Gets the value of the queryResult property.
     * 
     * @return
     *     possible object is
     *     {@link QueryResult }
     *     
     */
    public QueryResult getQueryResult() {
        return queryResult;
    }

    /**
     * Sets the value of the queryResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueryResult }
     *     
     */
    public void setQueryResult(QueryResult value) {
        this.queryResult = value;
    }

}
